### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by mingoscd**
post request data don't have the final character `}`

### CODE REVIEW

**Comment by BirgitBader** [comment]
@choffmeister please check and then merge this and the relating PR, thanks.

**Comment by choffmeister** [comment]
Are you sure that this is the problem? I just tested the current develop of the raml_parser without your fix by making the following changes:

```
diff --git a/spec/examples/raml/requestbodies.raml b/spec/examples/raml/requestbodies.raml
index f1d1ef8..ccb717c 100644
--- a/spec/examples/raml/requestbodies.raml
+++ b/spec/examples/raml/requestbodies.raml
@@ -19,3 +19,19 @@ baseUri: http://localhost:3000
             "status": "not found",
             "message: "Resource could not be found"
           }
+/second:
+  post:
+    body:
+      application/json:
+        example: |
+          {
+            "currency": "EUR",
+            "taxType": "GROSS",
+            "locale": "de_DE",
+            "lineItems": [
+              {
+                "productId": "prodGUID",
+                "quantity": 1
+              }
+            ]
+          }
diff --git a/spec/lib/raml_parser/snippet_generator_spec.rb b/spec/lib/raml_parser/snippet_generator_spec.rb
index 71bf724..461b05e 100644
--- a/spec/lib/raml_parser/snippet_generator_spec.rb
+++ b/spec/lib/raml_parser/snippet_generator_spec.rb
@@ -61,5 +61,10 @@ RSpec.describe RamlParser::SnippetGenerator do
     res3 = gen3.ruby(raml3.resources[4], 'get')
     expect(res3).to include 'Net::HTTP::Get'
     expect(res3).to include 'http://localhost:3000/i?l=value'
+
+    raml4 = RamlParser::Parser.parse_file('spec/examples/raml/requestbodies.raml')
+    gen4 = RamlParser::SnippetGenerator.new(raml4)
+    res4 = gen4.ruby(raml4.resources[1], 'post')
+    puts res4
   end
 end
```

The test output looks fine, even without this fix:

```
~/Development/raml_parser(branch:develop*) » rake test
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Library/Ruby/Gems/2.0.0/gems/rspec-support-3.2.2/lib:/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.2.3/lib /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
..require 'net/http'
require 'json'
uri = URI.parse('http://localhost:3000/second')
headers = {"Accept"=>"application/json"}
data = {
  "currency": "EUR",
  "taxType": "GROSS",
  "locale": "de_DE",
  "lineItems": [
    {
      "productId": "prodGUID",
      "quantity": 1
    }
  ]
}

req = Net::HTTP::Post.new(uri.path, initheader = headers)
req.body = data.to_json
response = Net::HTTP.start(uri.hostname, uri.port) { |http| http.request(req) }
..............................
```

_Note_: When writing a bugfix, please also add a test that fails without and succeeds with the fix in place to ensure, you have really done the task.

**Comment by mingoscd** [comment]
I'm sure that that is the bug
sc

**Comment by choffmeister** [comment]
Ok. Then you can merge it, deploy it and load it into epages-docs

Viele Gr��e
Christian Hoffmeister

Am 18.09.2015 um 10:07 schrieb Domingo <notifications@github.com<mailto:notifications@github.com>>:

I'm sure that that is the bug
[sc]https://cloud.githubusercontent.com/assets/5896360/9954878/d5d0231e-5dec-11e5-946c-d9fc3024dc1f.png

�

**Comment by choffmeister** [comment]
What is up with this PR? I though this fixes the bug?

**Comment by choffmeister** [comment]
Ah sry, there is a new PR for this. Did not see that :)

**Pull request closed without merging**
